version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make test
      - run: make coverage
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  main:
    jobs:
      - test:
          context: liftplan
